apiVersion: v2
name: rossoctl
description: A Helm chart for deploying the rossoctl platform
type: application
version: 0.7.0-rc.4
appVersion: "0.7.0-rc.4"

dependencies:
- name: operator-chart
  version: 0.3.0-rc.2
  repository: oci://ghcr.io/rossoctl/operator
  condition: components.agentOperator.enabled
