apiVersion: v2
name: rossoctl
description: A Helm chart for deploying the rossoctl platform
type: application
version: 0.8.0-rc.2
appVersion: "0.8.0-rc.2"

dependencies:
- name: operator-chart
  version: 0.4.0-rc.2
  repository: oci://ghcr.io/rossoctl/operator
  condition: components.agentOperator.enabled
